RibonDAO/interface

- generators/templates/context.test.tsx.hbs
> refactor: update test context file template

- src/components/moleculars/cards/CardFullImage/index.stories.tsx
- src/components/moleculars/cards/CardFullImage/index.test.tsx
- src/components/moleculars/cards/CardFullImage/index.tsx
- Fix card full image background prop
> fix: add backgroundImage prop to CardFullImage

- src/components/moleculars/cards/CardRoundImage/index.stories.tsx
- src/components/moleculars/cards/CardRoundImage/index.test.tsx
- src/components/moleculars/cards/CardRoundImage/index.tsx
- src/components/moleculars/cards/CardRoundImage/styles.ts
- src/config/testUtils/index.tsx
- feat: create component card round image
> feat: create component card round image

- src/index.tsx
- src/pages/donations/CausesPage/index.test.tsx
- src/services/index.ts
- Add sentry configurations
- Update `REACT_APP_SENTRY_ID` env var
> chore: add sentry config and initialize sentry

- src/components/moleculars/cards/CardRoundDoubleImage/index.stories.tsx
- src/pages/donations/DonationDonePage/index.tsx
- src/pages/donations/DonationDonePage/styles.ts
Adds DonationDonePage and CardRoundDoubleImage with tests  
> style: fixes button min-width

- src/contexts/currentUserContext/index.tsx
> feat: add currentUserContext

- src/config/routes/Navigation/index.tsx
- Add search to navigation links
We need this to maintain the search param between pages
> feat: add search to navigation links

- src/config/routes/Navigation/styles.ts
- src/styles/theme.ts
- Change color from white (#FFFFFF) to #FBFBFD
> fix: Adjust general pages background color

- README.md
- Add readme instructions about .env
- Add information about development, staging and production enviromnents
> docs: add enviroments and .env instructions to readme

- src/index.tsx
- src/pages/promoters/FundPage/index.tsx
- src/utils/abis/RibonAbi.json
- src/utils/contractUtils.ts
- Add donation pool balance to FundPage
- Add some contract helpers methods
> feat: add balanceOf and donationPoolBalance on fundPage

- package.json
- src/hooks/useBreakpoint/index.test.tsx
- yarn.lock
- Add tests to useBreakpoint hook
> test: add useBreakpoint tests

- public/locales/en/translation.json
- public/locales/pt/translation.json
- src/lib/web3Helpers/etherFormatters/index.test.ts
- src/lib/web3Helpers/etherFormatters/index.ts
- src/pages/promoters/FundPage/index.tsx
- src/pages/promoters/SupportFundPage/index.tsx
- Add usdc balance on SupportFundPage
> Add usdc balance to SupportFund

- public/locales/en/translation.json
- public/locales/pt/translation.json
- src/lib/formatters/stringToNumberFormatter/index.test.ts
- src/lib/formatters/stringToNumberFormatter/index.ts
- src/pages/promoters/SupportFundPage/index.tsx
- Add string to number converter
- Add validation to check if user has enough balance before donating
> Add usdc balance validation before donation

- .github/workflows/preview-deploy.yml
- .github/workflows/production-deploy.yml
- .github/workflows/staging-deploy.yml
- src/services/apiTheGraph/index.tsx
add enviroment variable to the graph api url
> feat: add enviroment variable to the graph api url

- src/pages/donations/CausesPage/index.tsx
> fix: add impactByTicket to ConfirmDonationModal

- src/config/testUtils/factories/impactFactory.ts
- src/hooks/apiHooks/useDonations/index.ts
- src/hooks/apiHooks/useImpact/index.ts
- src/pages/users/ImpactPage/index.test.tsx
- src/pages/users/ImpactPage/index.tsx
- Add logic to hide show more button in ImpactPage
> refactor: add logic to hide Show more button in ImpactPage

- public/locales/en/translation.json
- public/locales/pt/translation.json
- src/pages/promoters/FundPage/GivingsSection/index.tsx
Adds transaction error toast notification
> feat: adds transaction error toast

- src/components/moleculars/sliders/Carousel/index.tsx
- src/pages/promoters/FundPage/GivingsSection/index.tsx
> refactor: remove keen-slider div from GivingsSection components

- src/components/atomics/Button/index.test.tsx
- add tests to button component in order to be 100% tested
> feat: add tests to button component

- .github/workflows/ci.yml
- package.json
- src/pages/donations/DonationInProcessPage/index.test.tsx
- Add test coverage to ci
- fix it in 77% by now
> build: add test coverage to ci

- src/components/moleculars/modals/ModalBlank/styles.ts
- Remove unused styles from Modal Blank
> refactor: remove unused styles from ModalBlank

- src/pages/promoters/SupportFundPage/CardSection/FeesSection/index.tsx
- src/pages/promoters/SupportFundPage/CardSection/index.tsx
> fix: add useCallbacks to giving fees calculators

- src/components/atomics/LottieAnimation/index.tsx
- src/components/moleculars/cards/CardFullImage/index.test.tsx
- Add tests to the component cardFullImage to increase test coverage and ensure that the component works well
- closes #263
> fix: CardFullImage tests

- public/locales/en/translation.json
- public/locales/pt/translation.json
- public/manifest.json
- src/config/routes/Navigation/styles.ts
- src/layouts/MainLayout/styles.ts
- src/layouts/WalletLayout/styles.ts
- src/pages/donations/CausesPage/ConfirmEmail/index.tsx
- src/pages/promoters/SupportFundPage/CardSection/index.tsx
- src/pages/promoters/SupportFundPage/CardSection/styles.ts
- src/styles/globalStyle.ts
- src/utils/currency.ts
- Adjustments to card contribution price buttons
- Update privacy policy links
- Change background color of all screens to #FBFBFD
- closes #254 
- closes #251 
- closes #248 
> Fix/issues 254,251 and 248

- src/utils/currency.ts
- It was only working in english so this change will work with both languages
- I created that function to remove zero cents from the giving options buttons
> Fix removeInsignificantZeros function

- .github/workflows/ci-dependa-bot.yml
- .github/workflows/dependa-bot-pr-check.yml
- .github/workflows/preview-deploy.yml
- Update workflow to fix dependa bot checks
> build: update workflows files to fix dependa bot checks

- .github/workflows/ci-dependa-bot.yml
- Fix dependa bot workflow run
> fix: update dependa bot workflow run

- .storybook/main.js
> fix: add addon-actions to storybook main

- src/hooks/useWindowSize/index.test.tsx
Adds test to useWindowSize hook
> test: adds useWindowSize test

- src/pages/donations/CausesPage/index.tsx
- src/services/analytics/index.ts
- src/services/growthbook/index.tsx
- Analytics setUserid with installationId
> Analytics setUserid with installationId

- src/services/growthbook/index.tsx
- sending growthbook test ab to analytics
> fix:sending growthbook test ab to analytics

- public/locales/en/translation.json
- public/locales/pt/translation.json
Changes card donation text to match givings standard 
> refactor: changes individual card donation text

- src/services/growthbook/index.tsx
- Remove installation Id from Growthbook to verify if it interferes in the test.
> chore: remove installation id from growthbook attributes

- src/contexts/currentUserContext/index.tsx
- src/services/growthbook/index.tsx
> feat: add installation id and user_id from db in analytics when logged

- src/services/growthbook/index.tsx
- Remove toString from variationId from growthbook
> fix: remove toString

- src/App.tsx
- src/pages/donations/DonationDonePage/index.tsx
- src/services/analytics/index.test.ts
- src/services/analytics/index.ts
- src/services/growthbook/index.tsx
- Set installation id on local storage, before set attributes of growthbook
> Chore: Set installationId on localStorage and send to analytics 

- src/services/growthbook/index.tsx
- variationId of growthbook to string
> chore: variationId toString

- src/components/moleculars/cards/CardSelect/styles.ts
- src/components/moleculars/modals/ModalAnimation/styles.ts
- src/pages/promoters/FundPage/styles.ts
- src/pages/promoters/SupportFundPage/CardSection/styles.ts
> fix: colors name

- public/locales/en/translation.json
- public/locales/pt/translation.json
- src/contexts/networkContext/index.tsx
- src/hooks/useToast/index.ts
- src/layouts/LayoutHeader/LogoutItem/index.tsx
- src/layouts/WalletLayout/index.test.tsx
- src/layouts/WalletLayout/index.tsx
- src/styles/theme.ts
- Show a message error when connect in a invalid network
- Toast to show the message
- Condition to show connect in button when isn't connect a valid network
> feat: add condition to show toast when is invalid network

- src/pages/promoters/SupportTreasurePage/CardSection/ImpactInformationSection/index.tsx
- src/pages/promoters/SupportTreasurePage/CardSection/styles.ts
- The same as #477 but w/ the new folder structure.
> feature: dapp-404 redo

- src/services/analytics/index.test.ts
- src/services/analytics/index.ts
- Add integration id in log events to firebase
> feat: add integrationId in all logevents to firebase

- src/App.tsx
- src/layouts/LayoutHeader/index.test.tsx
- src/pages/donations/CausesPage/index.test.tsx
> fix: remove warnings on tests

- src/contexts/cardPaymentInformationContext/index.tsx
- src/hooks/apiHooks/useOffers/index.ts
- src/pages/promoters/SupportTreasurePage/CardSection/BillingInformationPage/index.tsx
- src/pages/promoters/SupportTreasurePage/CardSection/ImpactInformationSection/index.test.tsx
- src/pages/promoters/SupportTreasurePage/CardSection/ImpactInformationSection/index.tsx
- src/pages/promoters/SupportTreasurePage/CardSection/PaymentInformationPage/index.tsx
- src/pages/promoters/SupportTreasurePage/CardSection/index.tsx
> refactor: add currentOffer to card flow

- src/hooks/apiHooks/useNonProfitImpact/index.ts
> feat: add empty request to useNonProfitImpact

- .github/workflows/ci.yml
- Add pull request target to run CI
> build: add pull_request_target to ci.yml

- src/hooks/apiHooks/useIntegration/index.ts
- src/services/analytics/index.test.ts
- src/services/analytics/index.ts
> fix: adjust how call hook to integrationId

- src/config/networks/index.ts
- src/contexts/networkContext/index.test.tsx
- src/contexts/networkContext/index.tsx
- src/hooks/apiHooks/useContractBalance/index.ts
- src/pages/promoters/SupportTreasurePage/CryptoSection/index.tsx
- Fix some issues regarding balances across chains
> fix: add tokenDecimals as dependecy of userBalance

- src/config/abTest/features.ts
- src/layouts/MainLayout/index.tsx
- We decided to create a new one, so that the data wouldn't be interfered by our previous tests
> fix: new a/b test

- src/hooks/apiHooks/useIntegration/index.ts
- src/hooks/modalHooks/useAnimationReceiveTicketModal/index.tsx
- src/hooks/modalHooks/useDonationTicketModal/index.tsx
- src/pages/donations/CausesPage/index.tsx
> feat: adjust verification of integration name

- src/components/atomics/Dropdown/styles.ts
> refactor: centralizes input vertically

- src/hooks/apiHooks/useIntegration/index.ts
> fix: adjust to error

- README.md
- script.sh
- script to run dev environment
> feat: script to run dev environment

- src/contexts/cardPaymentInformationContext/index.tsx
- src/hooks/apiHooks/useCryptoTransaction/index.test.ts
- src/hooks/apiHooks/useCryptoTransaction/index.ts
- src/pages/promoters/SupportTreasurePage/CryptoSection/index.tsx
- src/services/api/creditCardPaymentApi/index.test.ts
- src/services/api/cryptoTransactionsApi/index.test.ts
- src/services/api/cryptoTransactionsApi/index.ts
- src/types/entities/CreditCardPayment.ts
- src/utils/constants.ts
- add integration_id when has contribution with credit card and crypto to add to person_payment 
- Add integration_id in params to credit card and crypto
- Adjust tests
> (tech-67) add integration_id when has contribution with credit card and crypto

- src/components/moleculars/cards/CardSideImageButton/index.test.tsx
- src/components/moleculars/cards/CardSideImageButton/index.tsx
- src/config/testUtils/expects.tsx
- Added tests to `CardSideImageButton`
- Closes #457
> test: add tests to CardSideImageButton

- src/pages/donations/CausesPage/index.tsx
> fix: remove console.log

- public/locales/en/translation.json
- public/locales/pt/translation.json
- src/pages/donations/CausesPage/NonProfitsList/index.tsx
A fancy loader to improve the story UX
https://user-images.githubusercontent.com/24739860/196788530-8b2acdcf-45de-4514-962c-af1f75ac9876.mp4
- Test A
> chore: story loader modal and toasts

- public/locales/en/translation.json
- public/locales/pt/translation.json
- src/lib/maskForTaxId/index.test.tsx
- src/lib/maskForTaxId/index.ts
- src/pages/promoters/SupportTreasurePage/CardSection/BillingInformationPage/BillingInformationSection/index.test.tsx
- src/pages/promoters/SupportTreasurePage/CardSection/BillingInformationPage/BillingInformationSection/index.tsx
- Add mask for tax id based on country
- Test A
> feat: add maskForTaxId based on country selected

- public/locales/en/translation.json
- public/locales/pt/translation.json
- src/pages/promoters/SupportTreasurePage/CryptoSection/index.test.tsx
- src/pages/promoters/SupportTreasurePage/CryptoSection/index.tsx
- src/pages/promoters/SupportTreasurePage/CryptoSection/styles.ts
- Add text in TreasurePage to tell user cryptos are not refundable
> feat: add text to tell user crypto are not refundable

- src/config/abTest/features.ts
- src/layouts/MainLayout/index.tsx
- Remove unused feature about menu from growthbook
- Remove condition to show or not show menu 
- Coments in features file
- closes [#TECH-144](https://ribon.atlassian.net/jira/software/c/projects/TECH/boards/26?modal=detail&selectedIssue=TECH-144)
- Verify if show menu just when after 1 donation
> (TECH-144) Remove unused feature from Growthbook

- src/hooks/modalHooks/useBlockedDonationModal/index.tsx
- Fix the condition to show integration tickets only when the integration has data on the integration task table 
- No.
- Test A
> fix: fix condition to show tickets

- src/config/routes/index.tsx
- src/contexts/cardPaymentInformationContext/index.tsx
- src/pages/promoters/SupportCausePage/SelectOfferSection/index.tsx
- Fix community add navigation loosing the previous page state
- Test A
> Fix community add navigation

- src/components/moleculars/modals/ModalAnimation/index.stories.tsx
- src/components/moleculars/modals/ModalAnimation/index.test.tsx
- src/components/moleculars/modals/ModalAnimation/index.tsx
- src/components/moleculars/modals/ModalAnimation/styles.ts
- Some improvements in the ModalAnimation, like custom colors and full size background for the circles (now diamonds). You can view in more details using storybook.
- Test A
> feat: dapp-573

- src/pages/donations/CausesPage/ConfirmDonationModal/index.tsx
- Change some modal icons
- Test A
> feat: change modal icons

- src/pages/donations/CausesPage/ConfirmDonationModal/index.tsx
Fix the NGO logo when it's in the confirm donation modal
- Test A
> fix: ngo logo sizing

- .github/workflows/production-deploy.yml
- Fixes the sentry not initializing on the dapp
- Test A
> fix: add REACT_APP_SENTRY_ID env to production-deploy.yml

- src/types/entities/User.ts
Add lastDonatedCause to users entity
The other part (set the button index based on the last cause) only can be merged after the @nathielymm's [PR](https://github.com/RibonDAO/interface/pull/702)
- Test A
> feat: dapp-358 (First part of the frontend)

- src/services/growthbook/index.tsx
- Add error handle to growthbook initialization
This is needed so we can investigate better what is the growthbook fetch error that is being popped in Sentry
- Test A
> fix: add error handle to growthbook init

- src/pages/donations/DonationDoneCausePage/index.tsx
- Add missing event on donation done
- Test A
> feat: add donateFinishedDonation_view event

- src/pages/donations/CausesPage/index.tsx
> hotfix: nonprofit slider on page refresh

- src/pages/donations/CausesPage/index.tsx
> fix: add nonprofits and cause as dependencies on bootup

- src/pages/promoters/SupportCausePage/CardPage/index.tsx
- src/pages/promoters/SupportCausePage/CryptoPage/index.tsx
- Update percentage of increase
- Test A
> chore: update percentage of increase to 20%

- src/hooks/modalHooks/useAnimationReceiveTicketModal/index.tsx
Same thing of previous reverted PR, but splitted
> fix: modal appearing after 1st donation

- src/pages/donations/CausesPage/index.tsx
Same as previous reverted PR but splitted /2
> fix: button index trigger by nonprofit

- src/pages/donations/CausesPage/index.tsx
Same as previous reverted PR, but splitted /3
> refactor: set causeid and index together

- src/pages/promoters/SupportCausePage/CardPage/index.tsx
- src/pages/promoters/SupportCausePage/CryptoPage/index.tsx
- Filter active causes on support pages
- Dapp-599
> fix: dapp-599

- src/pages/donations/CausesPage/ChooseCauseModal/CauseImage/styles.ts
- Add cursor pointer on cause image
- Add cursor pointer on cause image container
- eg: closes [#TECH-231](https://ribon.atlassian.net/jira/software/c/projects/TECH/boards/26/backlog?view=detail&selectedIssue=TECH-231&issueLimit=100)
> (TECH-231) Add cursor pointer on cause image

- .github/workflows/preview-deploy.yml
- Update preview deploy to use `development` env
- Test A
> build: update preview deploy to use development env

- src/pages/promoters/SupportCausePage/styles.ts
> fix: horizontal scrolling on the support cause page

- src/hooks/useLocationSearch/index.ts
- src/pages/promoters/SupportCausePage/CardPage/SelectOfferSection/index.tsx
- src/pages/promoters/SupportCausePage/CryptoPage/SelectCryptoOfferSection/index.tsx
- src/pages/promoters/SupportCausePage/index.tsx
- src/types/enums/Currencies.ts
- Update Support Cause page currency dropdown with USDC
- Test A
> fix: add usdc to dropdown of support cause page

- src/config/networks/index.ts
- src/contexts/cryptoPaymentContext/index.test.tsx
- src/contexts/networkContext/index.test.tsx
- update network with new contract
- Test A
> fix: update network with new contract

- src/contexts/cardPaymentInformationContext/index.tsx
- src/pages/donations/DonationDoneCausePage/index.tsx
- src/pages/donations/DonationDoneCausePage/styles.ts
- src/pages/donations/PostDonationPage/index.tsx
- src/pages/promoters/SupportCausePage/CryptoPage/index.tsx
- Adjust on donation done cause page to use in all types of donation
- Adjust style and condition to show components on donation done cause page
- Redirect to support cause or non profit page when donate
- Adjust redirect page on crypto donation
- Adjust images in donation done page and post donation page
- eg: closes [#DAPP-601](https://ribon.atlassian.net/jira/software/c/projects/DAPP/boards/22?modal=detail&selectedIssue=DAPP-601)
> (TECH-601, 615, 616) Adjust on donation done cause page

- public/locales/en/translation.json
- public/locales/pt/translation.json
- src/components/atomics/TicketWithTextAndImage/styles.ts
- src/components/moleculars/cards/CardStories/index.stories.tsx
- src/layouts/LayoutHeader/index.test.tsx
- Adjust copy and layout of modal tickets
- Adjust copy, change voucher to tickets
- Adjust layout of modal tickets
- eg: closes [#DAPP-620](https://ribon.atlassian.net/jira/software/c/projects/DAPP/boards/22?modal=detail&selectedIssue=DAPP-620)
> (DAPP-620, 625, 626) - Adjust copy and layout of modal tickets

- src/pages/promoters/SupportCausePage/CryptoPage/index.tsx
> fix: limit usdc value to 2 decimal places

- src/pages/donations/CausesPage/index.test.tsx
- src/pages/donations/CausesPage/index.tsx
- We didn't have a customer support card at causes page
- I inserted a customer support card there
- [#tech-287](https://ribon.atlassian.net/browse/TECH-287?atlOrigin=eyJpIjoiN2NjNDNiMjJkZGI1NDM3ZTgwNjQxYWY1MmViY2I5MjYiLCJwIjoiaiJ9)
- Go to CausesPage and check it
> feat: adds customer support section at causes page

- src/pages/donations/CausesPage/index.tsx
- src/pages/promoters/SupportNonProfitPage/styles.ts
- Adjust layout of Support Non Profits page and filter when is first access
- Adjust size of container cards to show 3 cards without arrows
- Add condition to filter and show just 1 cause when is first access
- eg: closes [#DAPP-612](https://ribon.atlassian.net/jira/software/c/projects/DAPP/boards/22?modal=detail&selectedIssue=DAPP-612)
> (DAPP-612) Adjust layout of Support Non Profits page and filter when is first access

- src/pages/promoters/SupportCausePage/CryptoPage/index.tsx
- set current pool when cause change
- Test A
> Tech 291: set correct pool for support cause

- README.md
- public/locales/en/translation.json
> Fix: typos

- src/pages/users/ImpactPage/index.test.tsx
- src/pages/users/ImpactPage/index.tsx
- remove "you donated" prefix from impact cards
- No
- Test A
> fix: remove prefix from impact cards

- src/components/moleculars/cards/CardTopImage/index.tsx
- src/components/moleculars/cards/CardTopImage/styles.ts
- src/pages/users/ImpactPage/ImpactMenu/CommunitySection/index.tsx
- src/pages/users/ImpactPage/ImpactMenu/DirectSection/index.tsx
- src/pages/users/ImpactPage/ImpactMenu/TicketSection/index.tsx
- src/pages/users/ImpactPage/ImpactMenu/styles.ts
- src/pages/users/ImpactPage/index.tsx
- src/pages/users/ImpactPage/styles.ts
- Adjust from impact menu
- eg: closes [#DAPP-639](https://ribon.atlassian.net/jira/software/c/projects/DAPP/boards/22?modal=detail&selectedIssue=DAPP-639)
> (DAPP-639) Adjust from impact menu

- src/lib/events/index.test.ts
- src/lib/events/index.ts
- src/services/analytics/firebase/index.test.ts
- src/services/analytics/firebase/index.ts
- src/services/analytics/mixpanel/index.test.ts
- src/services/analytics/mixpanel/index.ts
- Added mixpanel log event
- Test A
> Tech 299: Mixpanel log event

- src/components/atomics/buttons/ButtonToast/index.tsx
- src/components/moleculars/Toasts/DownloadAppToast/index.tsx
- src/layouts/LayoutHeader/GetTheAppItem/index.tsx
- src/pages/donations/DonationDoneCausePage/index.tsx
- src/pages/users/AppInDevelopmentPage/index.tsx
> fix: play sound only for free donations

- public/locales/en/translation.json
- public/locales/pt/translation.json
- src/pages/donations/CausesPage/index.test.tsx
- Changes the title and description texts from the support card
- DAPP-680
> chore: change support card text

- src/lib/events/index.test.ts
- src/lib/events/index.ts
- src/services/analytics/firebase/index.test.ts
- src/services/analytics/firebase/index.ts
- event params to string only on firebase
- Test A
> Fix: event params to string only on firebase

- src/lib/events/index.ts
- src/pages/donations/CausesPage/ConfirmEmail/index.tsx
- web_P1_loginForm_fill event is being logged multiple times
- Test A
> fix: log fill event only one time

- src/hooks/apiHooks/usePersonPayment/index.tsx
- src/pages/users/ImpactPage/ImpactMenu/CommunitySection/index.tsx
- src/pages/users/ImpactPage/ImpactMenu/DirectSection/index.tsx
- src/pages/users/ImpactPage/ImpactMenu/index.tsx
- src/services/api/personPaymentsApi/index.test.ts
- src/services/api/personPaymentsApi/index.ts
> hotfix: impact tab re-render and unexpected duplications

- src/pages/donations/CausesPage/index.tsx
- Counter ticket should be 0 until the receiving ticket modal closes 
https://user-images.githubusercontent.com/90937897/218756849-a236d31e-891c-486a-9e0b-c2947471b836.mov
- DAPP-675
> fix: adjust ticket counter

- src/hooks/apiHooks/useUsers/index.test.ts
- src/hooks/apiHooks/useUsers/index.ts
- src/pages/donations/CausesPage/StoriesSection/index.tsx
- src/pages/donations/CausesPage/index.tsx
- src/services/api/usersApi/index.test.ts
- src/services/api/usersApi/index.ts
> Tech 252: send language to create user

- src/pages/donations/CausesPage/StoriesSection/styles.ts
> fix: scroll in stories

- src/pages/donations/DonationDoneCausePage/styles.ts
- Fix flex vertical alignment of items on mobile, on the DonationDoneCause page
- Test A
> fix: flex alignment on mobile

- src/pages/donations/PostDonationPage/styles.ts
- button in post donation on mobile (actually just in **iphone SE** and small devices) is below of cards 
- eg: closes [#DAPP-649](https://ribon.atlassian.net/jira/software/c/projects/DAPP/boards/22?modal=detail&selectedIssue=DAPP-649)
> fix: button in post donation page in mobile

- src/config/zendesk/features.ts
- Open chat instead of form
- Support will be off for a few minutes, while me and Gisa do the configuration on zendesk interface
- Test A
> Tech 332: open chat on support button

- public/index.html
> Tech 334: hotjar

- src/config/zendesk/index.tsx
- these functions don't exists on messenger api
- Test A
> Fix: Zendesk webwidget to messenger

- src/components/atomics/inputs/InputAutoComplete/index.test.tsx
- src/components/atomics/inputs/InputAutoComplete/index.tsx
- Added tests to InputAutoComplete to secure 100% coverage
closes [#460 ]()
> feat: add tests to InputAutoComplete

- src/lib/events/index.ts
- fix integrationName false on events
- Test A
> fix: integrationName false

- src/pages/donations/CausesPage/NonProfitsList/index.tsx
- src/pages/donations/CausesPage/index.tsx
- When making a donation and then clicking donate later, the homepage button kept saying "donate ticket" instead of "no tickets", this PR fixes it
- Dapp-695
> fix: removes unexpect new voucher after donation

- src/components/atomics/inputs/InputText/styles.ts
- src/styles/globalStyle.ts
- Muri asked me some adjusts
- change 48dp to 24dp on global style
- change space between icons and text
- fix padding on focus and active
- Only on storybook
> Tech 385: material symbols fix

- craco.config.js
- package.json
- src/config/testUtils/index.tsx
- src/config/testUtils/renders.tsx
- src/hooks/useApi/index.tsx
- src/hooks/useContractRequest/index.tsx
- yarn.lock
- Add craco config files
- Fix react mismatch version error on link
- Test A
> fix: add craco and resolve react to fix yarn link

- src/contexts/cardPaymentInformationContext/index.tsx
- src/pages/donations/CausesPage/ConfirmSection/index.tsx
- src/pages/promoters/PaymentPage/index.tsx
- src/pages/promoters/SupportCausePage/CardPage/index.tsx
- Adjust donation done page to show correct image when is ticket donation and remove fallback image from donation to cause
- Remove modal about treasure when made a contribution
> Adjust donation done page to show correct image

- package.json
- src/types/entities/PersonPayment.ts
- yarn.lock
- Update guest to crypto user
- Test A
> fix: update guest to crypto_user

- package.json
- src/pages/donations/CausesPage/ConfirmSection/index.tsx
- src/utils/constants.ts
- yarn.lock
> feat: add platform param to identify when create a new donation

- .github/workflows/ci.yml
- this is for running lint and tests on forked branch
- Test A
> fix: ci for forked branch

- src/contexts/cardPaymentInformationContext/index.tsx
-  find or create a user when making a paid contribution without signing in 
- [DAPP-747](https://ribon.atlassian.net/browse/DAPP-747)
> feat: dapp-747

- src/hooks/useVoucher/index.test.tsx
- src/hooks/useVoucher/index.ts
Rollback to a local storage return for `isVoucherAvailable`
- Test A
> fix: use voucher bug

- public/locales/en/translation.json
- public/locales/pt/translation.json
- src/components/moleculars/modals/ModalError/index.test.tsx
- src/components/moleculars/modals/ModalError/index.tsx
- changes support link to whatsapp on modal error
- No.
> fix: change support link

- src/hooks/useFormattedImpactText/index.tsx
- src/utils/constants.ts
> fix: impact by ticket can be undefined

- src/components/moleculars/modals/ModalIcon/index.tsx
- Adjust the modal support link to redirect to WhatsApp 
-No
> fix: adjust support link to wpp

- .vscode/settings.json
- public/locales/en/translation.json
- public/locales/pt/translation.json
- src/contexts/tasksContext/index.tsx
- src/hooks/useCountdown/index.test.ts
- src/hooks/useCountdown/index.tsx
- src/lib/formatters/countdownFormatter/index.test.ts
- src/lib/formatters/countdownFormatter/index.ts
- src/lib/validators/index.test.tsx
- src/pages/users/ForYouPage/ForYouMenu/TasksSection/index.tsx
- src/pages/users/ForYouPage/ForYouMenu/TasksSection/styles.ts
Check daily news task;
Countdown timer;
- Test A
> feat: daily news task and countdown

- src/pages/users/ImpactPage/ImpactMenu/CommunitySection/index.tsx
- Add legacy contributions check to show impact cards on Community tab
- Test A
> fix: add legacy contributions check to show impact cards

- .github/workflows/ci.yml
- package.json
- yarn.lock
- adds the report coveralls to the github actions CI
- closes [DAPP-853](https://ribon.atlassian.net/browse/DAPP-853)
> chore: coveralls

- src/components/moleculars/modals/ModalDialog/index.stories.tsx
- src/components/moleculars/modals/ModalDialog/index.test.tsx
- src/components/moleculars/modals/ModalDialog/index.tsx
- src/components/moleculars/modals/ModalDialog/styles.ts
- src/contexts/modalContext/helpers.ts
- src/pages/users/ForYouPage/ForYouMenu/TasksSection/DailyTasksSection/styles.ts
- src/pages/users/ForYouPage/ForYouMenu/TasksSection/MonthlyTasksSection/index.tsx
- src/pages/users/ForYouPage/ForYouMenu/TasksSection/MonthlyTasksSection/styles.ts
- src/pages/users/ForYouPage/ForYouMenu/TasksSection/index.tsx
- src/styles/theme.ts
- Add new component of modal, in future we will remove this old's type of modal in next features and probably the context too. 
- Adjust layout of tasks
- eg: closes [#DAPP-781]()
> [DAPP-781] New component of modal

- src/pages/donations/DonationDoneCausePage/index.tsx
- src/pages/promoters/PaymentPage/index.tsx
- Use the new images and alt texts
- Test A
> refactor: ngo and cause images

- src/contexts/toastContext/toastComponent/index.test.tsx
- src/contexts/toastContext/toastComponent/index.tsx
- src/pages/promoters/PaymentPage/CardInfoSection/index.tsx
- adjust toast component and validation on expiration date
- eg: closes [#DAPP-873](https://ribon.atlassian.net/jira/software/c/projects/DAPP/boards/22/backlog?view=detail&selectedIssue=DAPP-873&issueLimit=100)
> fix: adjust toast component and validation on expiration date

- src/hooks/useLanguage/index.tsx
- src/lib/currentLanguage/index.ts
- src/pages/users/ImpactPage/index.test.tsx
- Fix first time default language
- Enter in an incognito tab and check if the language is set to the broswer language
> fix: update language default

- src/components/atomics/Tag/index.test.tsx
- src/lib/currentLanguage/index.test.ts
- src/pages/donations/CausesPage/ConfirmSection/index.test.tsx
- Add formattedShortLanguage tests
- Test A
> test: add formattedShortLanguage tests

- public/index.html
> Add smartlook

- src/pages/donations/CausesPage/ConfirmSection/index.tsx
- Add log error before page reload
- Test A
> fix: add log error to ConfirmSection

- public/locales/en/translation.json
- public/locales/pt/translation.json
- src/pages/users/ImpactPage/ImpactMigrationNotification/index.tsx
- change migration notification copy 
- Test A
> Tech 529: Change migration notification copy 

- src/hooks/useFormattedImpactText/index.test.ts
- src/services/api/personPaymentsApi/index.test.ts
-adds person payments and formatted impact text hook tests
-No.
- Test A
> test: adds person payments and formatted impact text hook tests

- src/config/routes/index.tsx
- src/hooks/toastHooks/useReceiveTicketToast/index.tsx
- src/layouts/LayoutHeader/index.test.tsx
- src/layouts/LayoutHeader/index.tsx
- src/lib/events/constants.ts
- src/pages/donations/GiveTicketPage/index.test.tsx
- src/pages/donations/GiveTicketPage/index.tsx
- src/pages/donations/LoadingPage/index.tsx
-  adds ticket page view events
- modifies routes to separate pages 
- No.
- 
- [] New feature (non-breaking change which adds functionality)
- Test A
> feat: onboarding-events

- public/locales/pt/translation.json
Just change a translaton. It was a request from the design review.
- Test A
> chore: change translation

- src/pages/donations/CausesPage/index.tsx
Remove app download modal for now
> fix: remove app download modal for a while

- src/pages/promoters/PaymentPage/index.tsx
- Adds set offerId on payment page to preserve pre selected offer 
- No
> fix: set offer on payment page

- src/layouts/MainLayout/index.tsx
- Fix main layout back button
- Test A
> fix: update main layout

- src/pages/donations/CausesPage/index.tsx
- contribution section duplicated
- Test A
> fix: contribution section duplicated

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/pages/promoters/PaymentPage/index.tsx
- src/pages/promoters/PaymentPage/styles.ts
- src/pages/promoters/PaymentPageV2/OfferSelection/index.tsx
https://github.com/RibonDAO/interface/assets/24739860/d4fb1b88-cf9e-43fc-aed0-0a1f5de56152
https://github.com/RibonDAO/interface/assets/24739860/7ecb7125-8fed-48d0-8719-c3aa64ea5b60
- Test A
> feat: new copy for additional fees

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/pages/promoters/PaymentPage/index.tsx
- src/pages/promoters/PaymentPage/styles.ts
- src/pages/promoters/PaymentPageV2/OfferSelection/index.tsx
Reverts RibonDAO/interface#1090
> Revert "feat: new copy for additional fees"

- package.json
- src/contexts/cardPaymentInformationContext/index.tsx
- src/contexts/cryptoPaymentContext/index.tsx
- src/pages/promoters/PaymentPage/index.test.tsx
- src/pages/promoters/PaymentPage/index.tsx
- src/pages/promoters/SupportCausePage/CardPage/index.tsx
- src/pages/promoters/SupportNonProfitPage/CardPage/index.tsx
- src/pages/promoters/SupportTreasurePage/CardSection/PaymentInformationPage/index.tsx
- src/pages/promoters/SupportTreasurePage/CryptoSection/index.tsx
- yarn.lock
> feat: add platform on crypto and credit card request

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/components/atomics/inputs/InputAutoComplete/index.tsx
- src/components/atomics/inputs/InputAutoComplete/styles.ts
- src/components/atomics/inputs/InputText/index.tsx
- src/pages/promoters/CheckoutPage/CardSection/index.tsx
- src/pages/promoters/CheckoutPage/CardSection/styles.ts
- src/pages/promoters/CheckoutPage/Components/CreditCardForm/index.test.tsx
- src/pages/promoters/CheckoutPage/Components/CreditCardForm/index.tsx
- src/pages/promoters/CheckoutPage/Components/CreditCardForm/styles.ts
Reverts RibonDAO/interface#1105
> Revert "Feat/credit card fiscal fields"

- src/components/moleculars/modals/ModalIcon/index.tsx
- src/layouts/LayoutHeader/UserSupportItem/index.tsx
- Adds two new logs for support button click
> feat: new event logs for support buttons

- src/pages/users/ImpactPage/ImpactMenu/CommunitySection/index.test.tsx
- src/pages/users/ImpactPage/ImpactMenu/CommunitySection/index.tsx
- src/pages/users/ImpactPage/ImpactMenu/DirectSection/index.test.tsx
- src/pages/users/ImpactPage/ImpactMenu/DirectSection/index.tsx
- Adds empty impact button events 
- No.
> feat: adds empty impact events

- src/hooks/useImpactConversion/index.tsx
- Use non profit impact to determines the impact value 
- closes [BUG](https://discord.com/channels/341989911450091522/1129013082673397770/1129013082673397770)
> fix: impact value

- src/pages/promoters/SupportCausePage/CardPage/index.tsx
- src/pages/promoters/SupportNonProfitPage/CardPage/index.tsx
- Add redirect to old checkout 
- Test A
> chore: temporary redirect to old checkout form

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/pages/promoters/CheckoutPage/CardSection/index.test.tsx
- src/pages/promoters/CheckoutPage/Components/CreditCardForm/index.test.tsx
- src/pages/promoters/CheckoutPage/Components/CreditCardForm/index.tsx
- src/pages/promoters/CheckoutPage/Components/PriceSelection/index.tsx
- ask for email when user is not signed
- show additional taxes copy only when offer is from stripe global
- Test A
> chore: payment form improvements

- src/pages/promoters/SupportCausePage/CardPage/index.tsx
- src/pages/promoters/SupportNonProfitPage/CardPage/index.tsx
> feat: checkout form launch

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/config/routes/Navigation/NavigationLink/index.tsx
- src/config/routes/Navigation/index.tsx
- src/config/routes/Navigation/styles.ts
- src/config/routes/index.tsx
- src/pages/promoters/SupportCauseFlowControlPage/index.test.tsx
- src/pages/promoters/SupportCauseFlowControlPage/index.tsx
- Add new copies to navigation links
- Add link to new landing pages
- Test A
> feat: add new label and copies to navigation link

- src/pages/donations/CausesPage/PromoterCta/styles.ts
- Fix responsive styles for promoter cta
- Adjust font sizes for mobile
- Test A
> style: fix mobile text styles in PromoterCta

- src/pages/users/ForYouPage/ForYouMenu/TasksSection/MonthlyTasksSection/index.tsx
- Remove promoter banner from for you page
- Test A
> feat: remove contribution banner from monthly tasks

- src/lib/events/constants.ts
- src/pages/donations/ConfirmDonationPage/SignedInSection/index.tsx
- src/pages/users/AppDownloadPage/AppDownloadTemplate/index.tsx
- src/pages/users/ForYouPage/ForYouMenu/NewsSection/index.tsx
- src/pages/users/ForYouPage/ForYouMenu/TasksSection/index.tsx
> feat: add missing events

- src/layouts/LayoutHeader/UserSupportItem/index.tsx
- src/pages/promoters/SupportTreasurePage/CardSection/UserSupportSection/index.tsx
> fix: fixes event name

- src/pages/users/ContributionStatsPage/index.tsx
- Add missing params and events to contribution stats flow
- Test A
> feat: add id param to contribution stats page events

- src/lib/events/index.test.ts
- src/lib/events/index.ts
- src/pages/donations/CausesPage/NonProfitsList/index.tsx
- src/pages/donations/CausesPage/index.tsx
- src/pages/donations/ConfirmDonationPage/SignInSection/index.test.tsx
- src/pages/donations/ConfirmDonationPage/SignInSection/index.tsx
- src/pages/donations/ConfirmDonationPage/index.tsx
- src/pages/donations/GiveTicketPage/index.test.tsx
- src/pages/donations/GiveTicketPage/index.tsx
- Add events and missing params to tickets flow
- Test A
> refactor: update event names and remove web_ prefix from newLogEvent

- src/hooks/useImpactConversion/index.tsx
- Uses control variation to disable impact test
-No
- Test A
> feat: disable impact test

- src/contexts/currentUserContext/index.tsx
- src/services/analytics/mixpanel/index.test.ts
- src/services/analytics/mixpanel/index.ts
- Add user id to mixpanel
- Test A
> feat: add setUserId to mixpanel

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/components/moleculars/cards/ContributionCard/index.test.tsx
- src/components/moleculars/cards/ContributionCard/index.tsx
- src/components/moleculars/cards/ContributionCard/styles.ts
- src/pages/donations/CausesPage/NonProfitsList/index.tsx
- src/pages/donations/DonationDoneCausePage/index.tsx
- src/pages/promoters/SupportNonProfitPage/CardPage/SelectOfferSection/index.tsx
Just a small A/B testing for that new card. 
NOTE: The prepositions are working well in production 😆 
> feat: progression ab testing for impression cards

- src/components/moleculars/cards/ContributionCard/index.test.tsx
- src/components/moleculars/cards/ContributionCard/index.tsx
test flag is hiding impression test. we should do it based on process env
> hotfix: test flag

- src/pages/donations/LoadingPage/index.tsx
- Fix integration name set on local storage
- Test A
> fix: add localstore set of integration name

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/pages/promoters/CheckoutPage/Components/PixForm/index.tsx
- src/pages/promoters/CheckoutPage/Components/PixForm/styles.ts
- src/pages/promoters/CheckoutPage/Components/PriceSelection/index.tsx
- Add pix receiver text
- Remove dollar charge aditional fees text
- Test A
> feat: remove adicional fees text and add pix text

- src/pages/donations/PostDonationPage/index.tsx
- post donation page links
- Test A
> PROD 151:  post donation page links

- src/pages/donations/CausesPage/index.tsx
- cta contribution section
- Test A
> prod 152: cta contribution section

- src/pages/promoters/CheckoutPage/Components/Header/index.test.tsx
- src/pages/promoters/CheckoutPage/Components/Header/index.tsx
- src/pages/promoters/CheckoutPage/Components/Header/styles.ts
- Fixs checkout back button behavior in order to back into the recurrence page
- Test A
> fix: checkout back button behavior

- src/lib/events/constants.ts
- src/lib/events/index.test.ts
- src/lib/events/index.ts
- src/pages/donations/LoadingPage/index.tsx
- Fix log event on P1
- Test A
> fix: add P1 log event in loading page

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/pages/promoters/CheckoutPage/Components/CreditCardForm/index.tsx
- src/pages/promoters/CheckoutPage/Components/PixForm/index.tsx
- Add min length to name on checkout forms
- Test A
> fix: add min length to name on checkout forms

- src/pages/promoters/CheckoutPage/Components/CreditCardForm/index.tsx
- Trying to activate gpay autocomplete
- Test A
> fix: input name card

- src/components/moleculars/cards/ContributionCard/index.test.tsx
- src/components/moleculars/cards/ContributionCard/index.tsx
- use offer instead of 0
- Test A
> fix: contribution card offer

- src/components/moleculars/cards/ContributionCard/styles.ts
- src/pages/donations/CausesPage/ContributionSection/index.tsx
- src/pages/donations/CausesPage/ContributionSection/styles.ts
- src/pages/donations/CausesPage/index.tsx
- limit image width
- remove text if 0 tickets
- Test A
> fix: style

- src/pages/donations/CausesPage/CausesSelectSection/index.test.tsx
- src/pages/donations/CausesPage/CausesSelectSection/index.tsx
- src/pages/donations/CausesPage/index.tsx
- Refactor causes page select cause section
- Test A
> refactor: add CausesSelectSection to CausesPage

- src/components/moleculars/cards/ContributionCard/index.test.tsx
- src/components/moleculars/cards/ContributionCard/index.tsx
- src/hooks/modalHooks/useBlockedDonationContributionModal/index.test.tsx
- src/hooks/modalHooks/useBlockedDonationContributionModal/index.tsx
- src/pages/users/ForYouPage/ForYouMenu/TasksSection/DailyTasksSection/index.tsx
- src/pages/users/ForYouPage/ForYouMenu/TasksSection/IntegrationTasksSection/index.tsx
- src/pages/users/ForYouPage/ForYouMenu/TasksSection/IntegrationTasksSection/styles.ts
- src/pages/users/ForYouPage/ForYouMenu/TasksSection/index.tsx
- src/pages/users/ForYouPage/ForYouMenu/TasksSection/styles.ts
- src/pages/users/ImpactPage/ImpactMenu/CommunitySection/index.test.tsx
- src/pages/users/ImpactPage/ImpactMenu/DirectSection/index.test.tsx
- on contribution card, redirect to recurrence page instead of checkout
- layout of integrationTasks
- fix offer from blockDonationContributionModal
- Test A
> prod-167: redirect to recurrence page

- src/components/moleculars/banners/UserSupportBanner/index.test.tsx
- src/pages/promoters/CheckoutPage/RecurrencePage/index.test.tsx
- src/pages/promoters/CheckoutPage/RecurrencePage/index.tsx
- Fix integration_id param on recurrence to checkout navigation
- Test A
> fix: add integration id param to recurrence page navigation

- src/pages/donations/CausesPage/StoriesSection/index.tsx
- sort stories by position
- Test A
> fix: sort stories

- src/pages/users/AppDownloadPage/index.tsx
- Use state to set non profit and show contribute just if has state
- eg: closes [#PROD3-175]()
- Test if in post donation the button has text "Skip"
- Test if when access the page app-download directly the button has text "back" and show the arrow to back
> [PROD3-175] Error on app-download page

- src/pages/donations/CausesPage/index.tsx
- src/pages/promoters/SupportCausePage/CardPage/index.tsx
- src/pages/promoters/SupportCausePage/CryptoPage/index.tsx
- src/pages/promoters/SupportNonProfitPage/CardPage/index.tsx
- Makes event parameters send a string with the current order of causes and non profits to make it easily accessible on mixpanel
> refactor: adjusts event parameters

- src/App.tsx
- src/config/testUtils/renders.tsx
- src/contexts/userLevelContext/index.test.tsx
- src/contexts/userLevelContext/index.tsx
- src/hooks/useUserLevel/index.tsx
- src/layouts/LayoutHeader/ImpactedLivesCounter/index.test.tsx
- src/layouts/LayoutHeader/ImpactedLivesCounter/index.tsx
- src/layouts/LayoutHeader/ImpactedLivesCounter/styles.ts
- src/layouts/LayoutHeader/index.tsx
- Add impacted lives to header
- Add useUserLevel hook
- Test A
> feat: add ImpactedLivesCounter and useUserLevel

- src/pages/donations/DonationDoneCausePage/index.tsx
- Fix donation done navigation
- Test A
> fix: update navigation after donation

- public/index.html
- Add facebook and google tags on public.index.js
> Add facebook and google tags on public.index.js

- src/layouts/LayoutHeader/ImpactedLivesCounter/index.test.tsx
- src/layouts/LayoutHeader/ImpactedLivesCounter/index.tsx
- src/pages/donations/DonationDoneCausePage/index.tsx
- src/pages/donations/PostDonationPage/index.tsx
- Add redirect to impact page if in life based impact flow
- Add navigation to lives impact counter
- Test A
> feat: add redirect to impact page if on lives impact flow

- src/hooks/useImpactConversion/index.tsx
- Adds nonProfitImpact to the dependency array to update the impact of the conversion CTA card on the causes page
- e.g.: update an environment variable
- eg: closes [Bug-Report](https://discord.com/channels/341989911450091522/1147246726424559719/1147246726424559719)
Put here all the things needed to test this PR and verify your changes, list any relevant details for tests (e.g.: have a wallet)
- Test A
> fix: dependency array

- src/contexts/cardPaymentInformationContext/index.tsx
- src/contexts/pixPaymentInformationContext/index.tsx
- src/hooks/useDonationFlow/index.tsx
- src/hooks/useNavigation/index.ts
- src/lib/getUTMFromLocationSearch/index.test.ts
- src/lib/getUTMFromLocationSearch/index.ts
- src/pages/donations/LoadingPage/index.tsx
- src/setupTests.ts
- src/utils/constants.ts
- redirect to deeplink
- New app version 5.2.0 on air
> feat: redirect to deeplink

- package.json
- src/hooks/useFormattedImpactText/index.test.ts
- src/pages/promoters/MonthlyContributionsPage/index.tsx
- yarn.lock
- added next_payment_attempt on subscriptions page
- Test A
> feat: added next_payment_attempt on subscriptions page

- src/pages/donations/LoadingPage/index.tsx
- only redirect on prod
- Test A
> fix: redirect to deeplink

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/hooks/useDonationFlow/index.tsx
- bug animation block DNN
- I don't know if this was the problem, but it's an attempt
- Test A
> fix: bug animation block DNN

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/components/moleculars/cards/ContributionCard/index.test.tsx
- src/contexts/userLevelContext/index.tsx
- src/hooks/useUserBadges/index.test.tsx
- src/pages/donations/CausesPage/NonProfitsList/index.tsx
- src/pages/promoters/SupportNonProfitPage/CardPage/SelectOfferSection/index.tsx
- src/pages/users/ImpactedLivesSection/ImpactedLivesCounter/index.test.tsx
- src/pages/users/ImpactedLivesSection/UserProgress/index.test.tsx
- src/pages/users/ImpactedLivesSection/UserProgress/index.tsx
- src/pages/users/ImpactedLivesSection/index.tsx
- Update lives counter to use proportional values from current level
- Update lives copy to people
- Test A
> refactor: update lives counter to use proportional values

- src/pages/promoters/SupportNonProfitPage/CardPage/ImpactLivesSection/index.tsx
- Fix UserProgress props
- Test A
> fix: add current level experience to UserProgress props

- src/components/moleculars/cards/CardLargeImage/index.stories.tsx
- src/components/moleculars/cards/CardLargeImage/index.test.tsx
- src/components/moleculars/cards/CardLargeImage/index.tsx
- src/components/moleculars/cards/CardLargeImage/styles.ts
- src/types/entities/ThemeShades.ts
> feat: add CardLargeImage component

- src/components/moleculars/banners/UserSupportBanner/index.tsx
- src/layouts/LayoutHeader/UserSupportItem/index.tsx
- Logs email parameter at the support click event
> fix: adds email to support event

- src/components/moleculars/banners/UserSupportBanner/index.tsx
- src/layouts/LayoutHeader/UserSupportItem/index.tsx
> fix: remove email

- src/layouts/LayoutHeader/UserSupportItem/index.tsx
- Renames the event 
- No.
- Test A
> fix: adjust support btn event

- src/components/moleculars/banners/InfoBanner/styles.ts
> fix: fixes image fitting

- src/hooks/useLanguage/index.tsx
- src/hooks/usePaymentParams/index.test.ts
- src/hooks/usePaymentParams/index.ts
- src/pages/promoters/CheckoutPage/RecurrencePage/index.test.tsx
- src/pages/promoters/CheckoutPage/RecurrencePage/index.tsx
> feat: add language param

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/components/moleculars/Toasts/InlineNotification/styles.ts
- src/hooks/usePaymentParams/index.test.ts
- src/hooks/usePaymentParams/index.ts
- src/pages/donations/CausesPage/NonProfitsList/index.tsx
- src/pages/promoters/CheckoutPage/FiatSection/index.tsx
https://github.com/RibonDAO/interface/assets/24739860/8721cf18-0e73-4f36-a31c-82fd3c3e684f
- Test A
> feat: ABC testing for the nonprofitslist

- package.json
- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/config/testUtils/factories/articleFactory.ts
- src/pages/users/ForYouPage/ForYouMenu/NewsSection/index.test.tsx
- src/pages/users/ForYouPage/ForYouMenu/NewsSection/index.tsx
- src/pages/users/ForYouPage/ForYouMenu/NewsSection/styles.ts
- yarn.lock
Reverts RibonDAO/interface#1327
> Revert "Revert "feat: adds block news""

- src/components/moleculars/cards/CardCenterImageButton/index.tsx
- src/components/moleculars/cards/CardCenterImageButton/styles.ts
- src/pages/donations/CausesPage/NonProfitsList/index.tsx
- changes cause/non profit name layout on non profit card so it fits better with bigger names
- [#prod3-199](https://ribon.atlassian.net/browse/PROD3-199?atlOrigin=eyJpIjoiOWM3OWUyZTRjYWMwNDI5MDg3NDEyOTUwMjNlNGZjNDMiLCJwIjoiaiJ9)
> chore: changes non profit card layout for title

- src/pages/promoters/SupportCausePage/styles.ts
- Fix layout breaking to some images in support cause
- Test A
> fix: update support image max height

- src/pages/donations/CausesPage/NonProfitsList/index.tsx
- Fix non profits list
- Test A
> fix: add navigation to checkout only when it doesnt have a voucher

- src/pages/donations/CausesPage/NonProfitsList/index.tsx
- src/pages/donations/CausesPage/index.tsx
- src/pages/promoters/CheckoutPage/FiatSection/index.tsx
Fixing a experiment name typo (due to a weird growthbook convention)
Checking if is in experiment to show understanding banner
> chore: some fixes and improvements in the AB test

- src/pages/donations/CausesPage/NonProfitsList/index.tsx
- src/pages/donations/CausesPage/styles.ts
- Add max width to donation cards
- Update donation cards width according to figma
- Test A
> style: add max width to donation cards

- src/components/moleculars/sliders/SliderCardsEnhanced/index.tsx
- src/pages/donations/CausesPage/NonProfitsSection/index.tsx
- src/pages/donations/CausesPage/index.tsx
- Move event handling to causes page sections
- Test A
> refactor: move donationCardsOrder_view event tlog to NonProfitsSection

- src/pages/donations/ConfirmDonationPage/index.tsx
- users were getting stuck on animation page so i added a navigateTo to see if it solves it
- Test A
> fix: animation bug

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/config/routes/index.tsx
- src/pages/campaigns/CampaignPage/index.tsx
- src/utils/constants/Tasks.ts
> feat: add campaign task

- src/pages/donations/CausesPage/CampaignSection/index.tsx
> fix: update campaign link

- src/contexts/causeDonationContext/index.tsx
- src/contexts/causesContext/index.tsx
- src/contexts/nonProfitsContext/index.tsx
- src/pages/donations/CausesPage/CausesSelectSection/index.test.tsx
- src/pages/donations/CausesPage/CausesSelectSection/index.tsx
- src/pages/donations/CausesPage/ChooseCauseModal/index.tsx
- src/pages/donations/CausesPage/NonProfitsSection/index.tsx
- src/pages/donations/CausesPage/index.test.tsx
- shows test causes and non profits for ribon emails
- [#prod3-180](https://ribon.atlassian.net/browse/PROD3-180?atlOrigin=eyJpIjoiODk0ZmMyMDNjNmFlNGFlY2IwZGZkN2I2ZWI5YzM1MTQiLCJwIjoiaiJ9)
> feat: shows test non profits for ribon emails

- src/components/moleculars/layouts/ArticleLayout/index.tsx
- src/pages/users/ForYouPage/ForYouMenu/NewsSection/index.tsx
> fix: posts event

- public/locales/pt-BR/translation.json
- Update campaign copy at navigation menu
> chore: update campaign copy at navigation menu

- src/hooks/useDonationFlow/index.tsx
- useIntegration removed because it is not necessary
- Test a free donation with every possibility
> fix: remove useIntegration

- public/locales/en/translation.json
- src/components/moleculars/banners/UserSupportBanner/index.test.tsx
- support translation
- Test A
> fix: support translation

- src/pages/donations/ConfirmDonationPage/index.tsx
- remove donationError message 
- Test A
> fix: remove donationError message 

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/components/moleculars/cards/CardCenterImageButton/index.tsx
- src/components/moleculars/cards/CardCenterImageButton/styles.ts
- src/pages/donations/CausesPage/NonProfitsList/index.tsx
- Add a second button in the NGO card redirecting to the checkout page. This is an AB test
- I'm also removing some mechanics from an old AB test
- Test A
> test: two buttons in ngo card text

- public/locales/pt-BR/translation.json
> chore: change some texts

- public/locales/pt-BR/translation.json
> chore: change copy

- public/locales/pt-BR/translation.json
- src/pages/donations/CausesPage/CampaignSection/index.tsx
- src/pages/donations/CausesPage/NonProfitsList/index.tsx
- src/utils/constants/Tasks.ts
remove some ab testing stuff and set some validated stuff as well
- Test A
> revert: old ab tests

- src/pages/auth/InsertEmailPage/index.tsx
- src/pages/donations/auth/InsertEmailAccountPage/index.tsx
- Adds async modifier on sendAuthenticationEmail 
> fix: adds async modifier on sendAuthenticationEmail

- src/contexts/cardPaymentInformationContext/index.tsx
- src/hooks/modalHooks/useAnimationReceiveTicketModal/index.tsx
- src/pages/donations/CausesPage/NonProfitsList/index.tsx
- src/pages/donations/ReceiveTicketPage/index.tsx
- src/pages/donations/auth/DonatingSection/index.tsx
- src/pages/donations/auth/ReceiveExtraTicketPage/index.tsx
- src/pages/users/ImpactedLivesSection/UserAvatar/styles.ts
- Adds user photo to all user icons 
- fix non profit list button
- fix integration id URL 
- fix profile avatar layout
- closes [PROD3-257](https://ribon.atlassian.net/browse/PROD3-257)
> feat: prod3-257

- src/pages/donations/CausesPage/index.tsx
- src/utils/constants.ts
- don't show integration banner
- change integration id to unique address
- Test A
> fix: integration banner

- src/pages/users/ImpactPage/ProfileSection/index.tsx
> fix: profile section without profile

- src/pages/users/ImpactedLivesSection/UserAvatar/styles.ts
- profile image width
- Test A
> fix: profile image width

- src/pages/donations/auth/InsertEmailAccountPage/styles.ts
- src/pages/donations/auth/SignInPage/styles.ts
- remove unecessary padding of sign in page on donations
- Check space of title and image on sign in page when donate
> feat: remove unecessary padding

- src/pages/auth/SignInExtraTicketPage/index.tsx
> fix: events name

- src/layouts/LayoutHeader/SettingsMenu/MonthlyContributions/index.test.tsx
- src/layouts/LayoutHeader/SettingsMenu/MonthlyContributions/index.tsx
- src/layouts/LayoutHeader/SettingsMenu/index.tsx
- src/pages/promoters/MonthlyContributionsPage/index.tsx
- calls the MonthlyContributions component on the menu 
- adds safe operator in an offer on the MonthlyContributions page
- No
> fix: settings-menu

- src/components/moleculars/cards/CardCampaign/index.tsx
> fix: recurrence default path

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/pages/donations/CausesPage/CampaignSection/index.tsx
- src/types/entities/ImpressionCard.ts
> feat: default impression card data

- src/pages/promoters/CheckoutPage/Components/ButtonSelectorTemplate/styles.ts
- src/utils/constants.ts
- yarn.lock
- Fix modal offer price selection height
- Verify if shows all prices and has scroll if necessary
> fix: modal offer

- package.json
- yarn.lock
- new shared version to persist cookies
- Check if you are still logged in after reloading
> fix: new shared version to persist cookies

- src/components/atomics/BottomBanner/styles.ts
- src/components/moleculars/Toasts/DownloadAppToast/index.tsx
- Just fixing mobile redirection and z-index for download toast
> fix: download toast issues

- src/pages/donations/CausesPage/NonProfitsSection/index.tsx
- src/pages/promoters/SupportCausePage/CardPage/index.tsx
- src/pages/promoters/SupportCausePage/CryptoPage/index.tsx
- src/pages/promoters/SupportNonProfitPage/CardPage/index.tsx
- remove order events 🎉
- Test A
> fix: remove order events

- package.json
- src/App.tsx
- src/contexts/ticketsContext/index.tsx
- src/contexts/toastContext/toastComponent/index.tsx
- src/hooks/toastHooks/useReceiveTicketToast/index.tsx
- src/hooks/useDonationFlow/index.tsx
- src/hooks/useTickets/index.ts
- src/pages/donations/CausesPage/NonProfitsList/index.tsx
- src/pages/donations/CausesPage/NonProfitsSection/index.tsx
- src/pages/donations/CausesPage/StoriesSection/index.tsx
- src/pages/donations/CausesPage/index.tsx
- yarn.lock
- Collect ticket by external id
- eg: closes [#PROD3-411]()
- Test if collect a ticket using external_id
> [PROD3-411] Collect ticket by external id

- src/services/api/index.ts
- Sends platform on headers
- [#prod3-433](https://ribon.atlassian.net/browse/PROD3-433?atlOrigin=eyJpIjoiYjQ2M2M4MzA4YTE5NDI2Mzk4YzllZDkwMDM1NWE1MmQiLCJwIjoiaiJ9)
- try to authenticate/refresh token and see the platform changing
> feat: sends platform on headers

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
> Fix: Prod3 413 translation

- src/pages/donations/GiveTicketPage/index.tsx
- src/pages/users/AppDownloadPage/AppDownloadTemplate/index.tsx
- pass integrationId on download app link
- Test A
> fix: pass integrationId on download app link

- src/pages/donations/auth/SignInPage/index.tsx
- added handleCollect before handleDonate
- Test A
> fix: added handleCollect before handleDonate

- src/lib/urlSignature/index.test.ts
- src/lib/urlSignature/index.ts
- src/pages/campaigns/redirectPage/index.tsx
- src/utils/constants.ts
Adds a SHA256 signature to URLs in order to avoid external people to use our /redirect to malicious links
NOTE: There will be a new page in our dApp manager to build signed links
> feat: sign redirect urls

- src/components/moleculars/cards/CardCheckbox/index.stories.tsx
- src/components/moleculars/cards/CardCheckbox/index.test.tsx
- src/components/moleculars/cards/CardCheckbox/index.tsx
- src/components/moleculars/cards/CardCheckbox/styles.ts
- src/components/moleculars/sections/GroupCardsCheckbox/index.stories.tsx
- src/components/moleculars/sections/GroupCardsCheckbox/index.test.tsx
- src/components/moleculars/sections/GroupCardsCheckbox/index.tsx
- src/components/moleculars/sections/GroupCardsCheckbox/styles.ts
- Adds card checkbox and group cards checkbox components with tests
- closes [PROD3-369](https://ribon.atlassian.net/browse/PROD3-369)
> feat: prod3-369

- src/hooks/useTickets/index.ts
- collect by integration parameters order
- Test A
> fix: collect by integration

- src/hooks/useDonationFlow/index.tsx
- https://ribon.sentry.io/issues/5013214543/?project=6175951&query=&referrer=issue-stream&sort=freq&statsPeriod=14d&stream_index=3
- Test A
> fix: status error

- src/hooks/useTickets/index.ts
- src/pages/donations/CausesPage/index.tsx
- src/pages/donations/auth/InsertEmailAccountPage/index.tsx
- src/pages/donations/auth/SignInPage/index.tsx
- src/pages/donations/auth/SignedInPage/index.tsx
- new event ticketCollected
- Test A
> feat: ticketCollected event

- src/pages/donations/auth/SignInPage/index.tsx
- donate on signIn Page onError
- Test A
> fix: Donate signIn page onError

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/pages/promoters/ContributionCanceledPage/index.tsx
- adds club canceled copy
- Test A
> feat: adds club canceled copy

- src/hooks/toastHooks/useReceiveTicketToast/index.tsx
- src/pages/donations/GiveTicketPage/index.tsx
- src/pages/donations/ReceiveTicketPage/index.tsx
- src/pages/donations/SelectTicketsPage/index.tsx
- Events review from https://www.notion.so/ribon-dev-docs/M-tricas-e-eventos-de-produto-q1-779239cadf98420989ed9cd7562587fa
- Review: https://www.notion.so/ribon-dev-docs/Revis-o-de-eventos-de-produto-q1-2024-club-94d2be349e8e4fccbf17b5eff706037c
- closes [PROD3-440](https://ribon.atlassian.net/browse/PROD3-440)
> fix:events

- src/pages/users/ImpactPage/ImpactMenu/index.tsx
> fix: remove red ball notif

- package.json
- yarn.lock
> feat: add new version of shared

- src/components/moleculars/sliders/SliderButton/index.test.tsx
- src/components/moleculars/sliders/SliderButton/index.tsx
- src/pages/donations/SelectTicketsPage/index.tsx
- slider button minimum number of tickets
- Test A
> prod 490: slider button minimum number of tickets

- src/pages/donations/CausesPage/index.tsx
> revert: show campaign card only if donated today

- package.json
- public/locales/en/translation.json
- src/contexts/cryptoPaymentContext/index.tsx
- src/pages/promoters/SupportNonProfitPage/CardPage/NonProfitCard/index.test.tsx
- src/pages/promoters/SupportNonProfitPage/CardPage/NonProfitCard/index.tsx
- src/pages/promoters/SupportNonProfitPage/CardPage/SelectOfferSection/index.test.tsx
- src/pages/promoters/SupportNonProfitPage/CardPage/SelectOfferSection/index.tsx
- src/pages/promoters/SupportNonProfitPage/CardPage/SelectOfferSection/styles.ts
- src/pages/promoters/SupportNonProfitPage/CardPage/index.tsx
- yarn.lock
- crypto contribution on support non profit
- check if non profit wallet is whitelisted
- go to /promoters/support-non-profit and try to make a contribution with usdc on mumbai network
> prod 528: crypto contribution on support non profit

- src/pages/donations/CausesPage/NonProfitsList/index.tsx
- removes blocking of listed nonprofits
- closes [PROD3-570](https://ribon.atlassian.net/browse/PROD3-570)
- Test A
> feat: prod3-570

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/contexts/authenticationContext/index.tsx
- src/pages/auth/SentMagicLinkEmailPage/index.test.tsx
- src/pages/auth/SentMagicLinkEmailPage/index.tsx
- src/pages/auth/SentMagicLinkEmailPage/styles.ts
- src/pages/auth/SignInPage/styles.ts
- src/pages/donations/CausesPage/NonProfitsList/index.tsx
- src/pages/donations/auth/SignInPage/index.test.tsx
- src/pages/donations/auth/SignInPage/index.tsx
- src/pages/donations/auth/SignInPage/styles.ts
- Change button magic link in first donation and change send magic link page without extra ticket.
- Click on a cause to make a donation and you will see the button in the footer that will redirect you to the authentication route.
> Chore/send magic link email page [PROD3-540 - PROD3-545]

- src/App.tsx
- comment growthbook provider
- Test A
> fix: comment growthbook

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/components/moleculars/FirstCard/index.test.tsx
- src/components/moleculars/FirstCard/index.tsx
- src/components/moleculars/FirstCard/styles.ts
- src/pages/donations/CausesPage/NonProfitsSection/index.tsx
- Add first card component
- the most practical way would be to change the NonProfitsSection page to this in the return, for example:
From this:
```
<S.NonProfitsContainer>
<NonProfitsList nonProfits={sortNonProfits()}
</S.NonProfitsContainer>
```
To this:
```
<S.NonProfitsContainer>
<FirstCard
nonProfit={sortNonProfits()[0]}
buttonOnClick={() => {}}
buttonDisabled={false}
ticketsQuantity={10}
/>
</S.NonProfitsContainer>
```
> Feat/first card [prod3-587]

- package.json
- src/config/testUtils/factories/nonProfitFactory.ts
- src/pages/donations/SelectTicketsPage/index.tsx
- src/pages/donations/SelectTicketsPage/styles.ts
- src/pages/donations/auth/InsertEmailAccountPage/index.tsx
- src/pages/donations/auth/InsertEmailAccountPage/styles.ts
- src/pages/donations/auth/SignInPage/index.tsx
- src/pages/donations/auth/SignInPage/styles.ts
- yarn.lock
> prod 597: nonProfit Icon

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/components/atomics/MadeByRibonPill/index.test.tsx
- src/components/atomics/MadeByRibonPill/index.tsx
- src/components/atomics/MadeByRibonPill/styles.ts
- src/pages/donations/CausesPage/MadeByRibonSection/index.test.tsx
- src/pages/donations/CausesPage/MadeByRibonSection/index.tsx
- src/pages/donations/CausesPage/MadeByRibonSection/styles.ts
- src/pages/donations/CausesPage/ReportsSection/index.tsx
- src/pages/donations/CausesPage/ReportsSection/styles.ts
- src/pages/donations/CausesPage/index.test.tsx
- src/pages/donations/CausesPage/index.tsx
- src/pages/donations/CausesPage/styles.ts
- Remove support card
- Add white label bottom bar
> feat: made by ribon bottom bar

- src/contexts/ticketsContext/index.tsx
- src/hooks/apiHooks/useDonateTickets/index.ts
- src/hooks/useCollectTickets/index.ts
- src/hooks/useDonationFlow/index.test.tsx
- src/hooks/useDonationFlow/index.tsx
- src/pages/donations/CausesPage/index.tsx
- src/pages/donations/GiveTicketPage/index.tsx
- src/pages/donations/SelectTicketsPage/index.tsx
- src/pages/donations/auth/SignInPage/index.tsx
- src/services/api/ticketsApi/index.ts
- allow donate without authentication
- Test A
> prod 598: allow donate without authentication

- public/index.html
> feat: metatags for title and desscription

- src/App.tsx
- src/components/moleculars/sliders/SliderCardsEnhanced/index.test.tsx
- src/components/moleculars/sliders/SliderCardsEnhanced/index.tsx
- src/contexts/nonProfitsContext/index.tsx
- src/contexts/tagDonationContext/index.tsx
- src/pages/donations/CausesPage/ChooseCauseModal/CauseImage/index.tsx
- src/pages/donations/CausesPage/NonProfitsListCarousel/NonProfitComponent/index.tsx
- src/pages/donations/CausesPage/NonProfitsListCarousel/NonProfitComponent/styles.ts
- src/pages/donations/CausesPage/NonProfitsListCarousel/index.tsx
- src/pages/donations/CausesPage/NonProfitsSection/index.tsx
- src/pages/donations/CausesPage/TagsSelectSection/index.tsx
- sort non profits randomically
- verify if order of non profits is random
> fix: sort non profits randomically 

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/pages/donations/auth/SignInPage/index.test.tsx
- src/pages/donations/auth/SignInPage/index.tsx
- src/pages/donations/auth/SignInPage/styles.ts
- new copy and color in title and impact text
- closes [PROD3-658](https://ribon.atlassian.net/browse/PROD3-658)
> chore: new copy and color

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/App.tsx
- src/contexts/currentUserContext/index.tsx
- src/contexts/integrationContext/index.tsx
- src/contexts/ticketsContext/index.tsx
- src/hooks/toastHooks/useReceiveTicketToast/index.tsx
- src/hooks/useCollectTickets/index.ts
- src/layouts/LayoutHeader/index.test.tsx
- src/pages/donations/CausesPage/index.test.tsx
- src/pages/donations/CausesPage/index.tsx
- src/pages/donations/GiveTicketPage/index.test.tsx
- src/pages/donations/GiveTicketPage/index.tsx
- src/pages/donations/LoadingPage/index.tsx
- src/pages/donations/auth/InsertEmailAccountPage/index.tsx
- src/pages/donations/auth/SignInPage/index.tsx
- src/pages/onboarding/FirstPage/index.tsx
- show how many tickets the user can collect on onboarding
- collect tickets after login
- only show give-tickets page when click on toast
- Test A
> fix: show how many tickets on onboarding

- src/components/atomics/Markdown/styles.ts
Fixes markdown styling for a few elements
[figma-adjustments-link](https://www.figma.com/design/EtC61gUYYVjXFQwCUDcUWV/Escolha-e-seleção-de-ONGs-%2F-Perfil?node-id=3751-650&t=tWPCL6Bt1RZLV2Cg-4)
> fix: markdown style

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/config/routes/index.tsx
- src/contexts/integrationContext/index.tsx
- src/contexts/ticketsContext/index.tsx
- src/layouts/MainLayout/index.tsx
- src/pages/auth/SentMagicLinkEmailPage/index.tsx
- src/pages/auth/SentMagicLinkEmailPage/styles.ts
- src/pages/donations/CausesPage/index.test.tsx
- src/pages/donations/LoadingPage/index.tsx
- src/pages/onboarding/FirstPage/index.tsx
- show tickets based on externalIds length
- Test A
> fix: show tickets based on externalIds length

- public/index.html
> chore: new seo description

- public/locales/en/translation.json
- public/locales/pt-BR/translation.json
- src/contexts/integrationContext/index.tsx
- src/contexts/tasksContext/index.tsx
- src/contexts/ticketsContext/index.tsx
- src/contexts/toastContext/toastComponent/index.tsx
- src/contexts/toastContext/toastComponent/styles.ts
- src/hooks/useCollectTickets/index.ts
- src/hooks/useDonationFlow/index.tsx
- src/pages/donations/CausesPage/index.tsx
- src/pages/donations/GiveTicketPage/index.tsx
- src/pages/donations/LoadingPage/index.tsx
- src/pages/donations/SelectTicketsPage/index.tsx
- set integration and externalId on integrationContext
- Test A
> Fix/dnn: set integration and externalId on integrationContext

- src/hooks/modalHooks/useUnauthorizedContributionModal/index.test.tsx
- src/hooks/modalHooks/useUnauthorizedContributionModal/index.tsx
- src/pages/donations/CausesPage/MadeByRibonSection/index.test.tsx
- src/pages/donations/CausesPage/NonProfitsList/index.test.tsx
- src/pages/donations/CausesPage/NonProfitsListCarousel/index.tsx
- blocks contributions for non authenticated users
- Test A
> feat: prod3/718

- src/pages/donations/LoadingPage/index.tsx
- src/utils/constants.ts
> fix: magic link

- package.json
- src/config/testUtils/factories/impactFactory.ts
- src/layouts/LayoutHeader/index.tsx
- src/layouts/LayoutHeader/styles.ts
- src/layouts/MainLayout/index.tsx
- src/pages/users/ImpactPage/ProfileSection/index.tsx
- src/pages/users/ImpactPage/ProfileSection/styles.ts
- src/pages/users/ImpactPage/UserAvatar/index.test.tsx
- src/pages/users/ImpactPage/UserAvatar/index.tsx
- src/pages/users/ImpactPage/index.tsx
- yarn.lock
- renames from isMember to isClubMember
- update shared
- closes [PROD3-683](https://ribon.atlassian.net/browse/PROD3-683)
- Test A
> fix: prod3-683

- src/contexts/authenticationContext/index.tsx
- src/pages/auth/ExpiredLinkPage/index.test.tsx
- src/pages/donations/auth/InsertEmailAccountPage/index.tsx
- src/pages/donations/auth/InsertEmailAccountPage/styles.ts
-  it was showing this modal, because it was collecting after the user try to donate
- Test A
> fix: login, collect and wait to proceed

- public/locales/pt-BR/translation.json
- fix post donation page translation prefix
> fix: translation

- src/pages/donations/SelectTicketsPage/index.tsx
- src/pages/donations/TicketDonationDonePage/index.tsx
- Adjust ticketDonated_end  event 
- closes [PROD3-708](https://ribon.atlassian.net/browse/PROD3-708)
> fix: ticket donated event

- src/pages/onboarding/FirstPage/styles.ts
> fix: image size

- src/contexts/integrationContext/index.tsx
- external_id with %2C
- Test A
> fix: dnn external_id with %2C

- src/contexts/integrationContext/index.tsx
- src/pages/donations/LoadingPage/index.tsx
> Fix: external id dnn
